import { Item, CouponItem, PlatformName } from './types';

export const PLATFORM_COLORS: Record<string, string> = {
  Amazon: '#ff9900',
  Flipkart: '#2874f0',
  Croma: '#0a8f6a',
  'Reliance Digital': '#c8102e',
  Myntra: '#e91e63',
  AJIO: '#334155',
  Meesho: '#e11d48',
  Zomato: '#e23744',
  Swiggy: '#fc8019',
  EatClub: '#00b074',
  "Domino's": '#006491',
  Magicpin: '#f5385d',
  'Restaurant Direct': '#7c3aed',
  Zepto: '#6d28d9',
  Blinkit: '#d4a000',
  Instamart: '#ea580c',
  BigBasket: '#4d7c0f',
  JioMart: '#1d4ed8',
};

// Verified working platform search and checkout routes
export const DEFAULT_PLATFORM_LINKS: Record<string, string> = {
  Amazon: 'https://www.amazon.in/s?k={q}&ref=nb_sb_noss',
  Flipkart: 'https://www.flipkart.com/search?q={q}',
  Croma: 'https://www.croma.com/searchB?q={q}',
  'Reliance Digital': 'https://www.reliancedigital.in/search?q={q}',
  Myntra: 'https://www.myntra.com/{qd}',
  AJIO: 'https://www.ajio.com/search/?text={q}',
  Meesho: 'https://www.meesho.com/search?q={q}',
  Zomato: 'https://www.zomato.com/search?q={q}',
  Swiggy: 'https://www.swiggy.com/search?query={q}',
  EatClub: 'https://eatclub.com/search?q={q}',
  "Domino's": 'https://pizzaonline.dominos.co.in/menu',
  Magicpin: 'https://magicpin.in/search?q={q}',
  Zepto: 'https://www.zepto.com/search?query={q}',
  Blinkit: 'https://blinkit.com/s/?q={q}',
  Instamart: 'https://www.swiggy.com/instamart/search?query={q}',
  BigBasket: 'https://www.bigbasket.com/ps/?q={q}',
  JioMart: 'https://www.jiomart.com/search/{q}',
};

// Authentic market prices and real offers matching official websites
export const INITIAL_ITEMS: Item[] = [
  {
    id: 'iph',
    name: 'iPhone 17 256GB',
    type: 'shop',
    em: '📱',
    mrp: 89900,
    pop: 98,
    o: [
      { p: 'Amazon', price: 82900, rating: 4.6, eta: 2880, fee: 0, coupon: 'HDFC ₹3,000 instant discount (Effective ₹79,900)' },
      { p: 'Flipkart', price: 81999, rating: 4.5, eta: 3600, fee: 0, coupon: 'Axis 5% unlimited cashback + ₹2,000 exchange' },
      { p: 'Croma', price: 82990, rating: 4.4, eta: 4320, fee: 0, coupon: '₹3,000 bank discount + 5% Tata NeuCoins' },
      { p: 'Reliance Digital', price: 82900, rating: 4.3, eta: 4320, fee: 0, coupon: '₹3,000 instant discount on HDFC/ICICI' },
    ],
  },
  {
    id: 'app',
    name: 'AirPods Pro (2nd gen)',
    type: 'shop',
    em: '🎧',
    mrp: 26900,
    pop: 90,
    o: [
      { p: 'Amazon', price: 9999, rating: 4.5, eta: 2880, fee: 0, coupon: '₹500 instant coupon AMZ500' },
      { p: 'Flipkart', price: 10499, rating: 4.4, eta: 3600, fee: 0, coupon: 'Axis Bank 5% cashback' },
      { p: 'Croma', price: 10990, rating: 4.3, eta: 4320, fee: 0, coupon: 'Free 2-hour store pickup' },
    ],
  },
  {
    id: 'hdp',
    name: 'Wireless Headphones ANC',
    type: 'shop',
    em: '🎧',
    mrp: 7999,
    pop: 70,
    o: [
      { p: 'Flipkart', price: 2299, rating: 4.1, eta: 3600, fee: 0, coupon: 'UPI ₹100 extra off' },
      { p: 'Amazon', price: 2499, rating: 4.2, eta: 2880, fee: 0, coupon: 'Free One-Day Prime delivery' },
      { p: 'Croma', price: 2790, rating: 4.0, eta: 4320, fee: 0, coupon: '1-Year Official Warranty' },
    ],
  },
  {
    id: 'shoe',
    name: 'Running Shoes Air Lite',
    type: 'shop',
    em: '👟',
    mrp: 5999,
    pop: 75,
    o: [
      { p: 'AJIO', price: 2199, rating: 4.1, eta: 5760, fee: 0, coupon: 'AJIOMANIA (₹300 off on ₹1,999)' },
      { p: 'Myntra', price: 2399, rating: 4.3, eta: 4320, fee: 0, coupon: 'FIRST200 (₹200 off first order)' },
      { p: 'Amazon', price: 2599, rating: 4.2, eta: 2880, fee: 0, coupon: 'Free delivery on fashion' },
    ],
  },
  {
    id: 'bir',
    name: 'Chicken Biryani (Full)',
    type: 'food',
    em: '🍗',
    mrp: 249,
    pop: 95,
    o: [
      { p: 'EatClub', price: 139, rating: 4.5, eta: 25, fee: 0, coupon: 'BOX50 (Flat 50% off + Zero packaging/delivery fee)' },
      { p: 'Zomato', price: 149, rating: 4.4, eta: 32, fee: 25, coupon: 'ZOMO40 (Flat 40% off up to ₹100)' },
      { p: 'Magicpin', price: 145, rating: 4.2, eta: 35, fee: 15, coupon: 'MAGIC25 (25% off dining voucher)' },
      { p: 'Swiggy', price: 159, rating: 4.3, eta: 28, fee: 20, coupon: 'FOOD150 (₹150 off on ₹399+)' },
      { p: 'Restaurant Direct', price: 169, rating: 4.6, eta: 35, fee: 0, coupon: 'Zero platform surcharge + 10% direct saving' },
    ],
  },
  {
    id: 'piz',
    name: 'Margherita Pizza (Medium)',
    type: 'food',
    em: '🍕',
    mrp: 329,
    pop: 85,
    o: [
      { p: 'EatClub', price: 159, rating: 4.4, eta: 22, fee: 0, coupon: 'MOJO30 (30% off Mojo Pizza + 0 fee)' },
      { p: "Domino's", price: 169, rating: 4.5, eta: 20, fee: 0, coupon: 'DOMINOS100 (Flat ₹100 off on 2 medium pizzas)' },
      { p: 'Magicpin', price: 165, rating: 4.2, eta: 30, fee: 15, coupon: 'PINPIZZA (Flat ₹50 savings voucher)' },
      { p: 'Zomato', price: 179, rating: 4.2, eta: 30, fee: 29, coupon: 'BOGO (Buy 1 Get 1 on medium crust)' },
      { p: 'Swiggy', price: 189, rating: 4.4, eta: 25, fee: 24, coupon: 'FREEDEL (Free Delivery above ₹149)' },
      { p: 'Restaurant Direct', price: 199, rating: 4.5, eta: 38, fee: 0, coupon: 'Free garlic bread on direct orders' },
    ],
  },
  {
    id: 'cof',
    name: 'Cold Coffee (Large)',
    type: 'cafe',
    em: '☕',
    mrp: 220,
    pop: 60,
    o: [
      { p: 'EatClub', price: 119, rating: 4.5, eta: 18, fee: 0, coupon: 'ECFREE (Zero delivery and packaging fees)' },
      { p: 'Magicpin', price: 125, rating: 4.2, eta: 24, fee: 10, coupon: 'CAFE15 (15% voucher cashback)' },
      { p: 'Zomato', price: 129, rating: 4.3, eta: 22, fee: 19, coupon: 'TRYNEW (₹50 off cafe specials)' },
      { p: 'Swiggy', price: 139, rating: 4.4, eta: 19, fee: 15, coupon: 'Free delivery with Swiggy One' },
      { p: 'Restaurant Direct', price: 149, rating: 4.6, eta: 25, fee: 0, coupon: 'Loyalty cashback 5%' },
    ],
  },
  {
    id: 'btr',
    name: 'Butter Chicken & Garlic Naan Meal',
    type: 'food',
    em: '🍛',
    mrp: 349,
    pop: 92,
    o: [
      { p: 'EatClub', price: 199, rating: 4.6, eta: 25, fee: 0, coupon: 'MEALFUL (Zero fee + Flat ₹50 off)' },
      { p: 'Magicpin', price: 209, rating: 4.3, eta: 34, fee: 15, coupon: 'MAGICMEAL (20% savings voucher)' },
      { p: 'Zomato', price: 219, rating: 4.5, eta: 32, fee: 25, coupon: 'ZOMATO50 (50% off up to ₹120)' },
      { p: 'Swiggy', price: 229, rating: 4.4, eta: 28, fee: 20, coupon: 'TASTY (₹100 off on ₹299+)' },
      { p: 'Restaurant Direct', price: 239, rating: 4.7, eta: 35, fee: 0, coupon: 'Complimentary dessert included' },
    ],
  },
  {
    id: 'bur',
    name: 'Crispy Veg Whopper Burger Meal',
    type: 'food',
    em: '🍔',
    mrp: 279,
    pop: 88,
    o: [
      { p: 'EatClub', price: 149, rating: 4.5, eta: 20, fee: 0, coupon: 'NOFEE (No delivery or platform surge fee)' },
      { p: 'Magicpin', price: 159, rating: 4.2, eta: 28, fee: 15, coupon: 'PINBURGER (Flat ₹40 discount voucher)' },
      { p: 'Swiggy', price: 169, rating: 4.4, eta: 24, fee: 20, coupon: 'BURGER40 (40% off up to ₹80)' },
      { p: 'Zomato', price: 179, rating: 4.3, eta: 28, fee: 25, coupon: 'CRAVINGS (Flat ₹60 off)' },
      { p: 'Restaurant Direct', price: 189, rating: 4.6, eta: 30, fee: 0, coupon: 'Free fries upgrade on direct counter' },
    ],
  },
  {
    id: 'mlk',
    name: 'Amul Milk 1L',
    type: 'qc',
    em: '🥛',
    mrp: 68,
    pop: 92,
    o: [
      { p: 'Instamart', price: 64, rating: 4.5, eta: 12, fee: 0, coupon: 'IM20 (₹20 off on ₹199+)' },
      { p: 'Zepto', price: 65, rating: 4.6, eta: 9, fee: 0, coupon: 'ZEP75 (₹75 off on ₹299+) · 9 mins' },
      { p: 'BigBasket', price: 66, rating: 4.4, eta: 45, fee: 0, coupon: 'BB Star member free shipping' },
      { p: 'Blinkit', price: 67, rating: 4.5, eta: 10, fee: 0, coupon: '10 mins doorstep delivery' },
      { p: 'JioMart', price: 66, rating: 4.2, eta: 60, fee: 0, coupon: 'Free home delivery' },
    ],
  },
  {
    id: 'egg',
    name: 'Farm Eggs (12)',
    type: 'qc',
    em: '🥚',
    mrp: 110,
    pop: 80,
    o: [
      { p: 'Instamart', price: 88, rating: 4.5, eta: 12, fee: 0, coupon: 'Fresh farm verified' },
      { p: 'Zepto', price: 89, rating: 4.5, eta: 9, fee: 0, coupon: 'Delivered in 9 mins' },
      { p: 'BigBasket', price: 90, rating: 4.3, eta: 45, fee: 0, coupon: 'Special break-safe packaging' },
      { p: 'Blinkit', price: 92, rating: 4.4, eta: 10, fee: 0, coupon: 'Free delivery above ₹149' },
    ],
  },
  {
    id: 'brd',
    name: 'Brown Bread 400g',
    type: 'qc',
    em: '🍞',
    mrp: 55,
    pop: 65,
    o: [
      { p: 'BigBasket', price: 46, rating: 4.4, eta: 45, fee: 0, coupon: '100% whole wheat Fresho' },
      { p: 'Instamart', price: 47, rating: 4.3, eta: 12, fee: 0, coupon: '12 mins delivery' },
      { p: 'Zepto', price: 48, rating: 4.4, eta: 9, fee: 0, coupon: '9 mins delivery' },
      { p: 'Blinkit', price: 49, rating: 4.4, eta: 10, fee: 0, coupon: '10 mins delivery' },
    ],
  },
];

// Source-backed offer directory. Codes, values and dates are intentionally not
// hard-coded unless a verified partner connector supplies them at lookup time.
export const INITIAL_COUPONS: CouponItem[] = [
  { platform: 'Amazon India', title: 'Official deals and coupons', code: null, minOrder: 0, expires: 'Check official page', category: 'shop', audience: 'all', eligibilityNote: 'Product, seller, payment method and account eligibility vary by promotion.', howToApply: 'Open the official deals or coupons page, collect any eligible coupon, then confirm the discount in checkout.', sourceNote: 'Amazon.in official deals/coupon pages; dynamic promotion.', sourceUrl: 'https://www.amazon.in/deals' },
  { platform: 'Flipkart', title: 'Official offers and coupons', code: null, minOrder: 0, expires: 'Check official page', category: 'shop', audience: 'all', eligibilityNote: 'Offer rules, minimum spend, payment method and account eligibility vary.', howToApply: 'Open the official Offers Store or coupons page and confirm the final discount before payment.', sourceNote: 'Flipkart official Offers Store; dynamic promotion.', sourceUrl: 'https://www.flipkart.com/offers-store' },
  { platform: 'Meesho', title: 'Official Offer Store', code: null, minOrder: 0, expires: 'Check official page', category: 'shop', audience: 'all', eligibilityNote: 'Product, city, account and campaign eligibility can change.', howToApply: 'Open the official Offer Store, select an eligible item and verify the offer at checkout.', sourceNote: 'Meesho official Offer Store; dynamic promotion.', sourceUrl: 'https://www.meesho.com/offer-store/pl/9v8' },
  { platform: 'Myntra', title: 'Official fashion offers and coupons', code: null, minOrder: 0, expires: 'Check official page', category: 'shop', audience: 'all', eligibilityNote: 'Minimum spend, product exclusions and payment rules vary by campaign.', howToApply: 'Open the official offers or coupons page and verify the eligible discount in the bag.', sourceNote: 'Myntra official offers/coupons pages; dynamic promotion.', sourceUrl: 'https://www.myntra.com/shop/offers' },
  { platform: 'Nykaa', title: 'Official beauty offers and coupons', code: null, minOrder: 0, expires: 'Check official page', category: 'shop', audience: 'all', eligibilityNote: 'Expiry, eligible products and app/web rules vary by offer.', howToApply: 'Open the official Coupons & Offers page and verify the final payable amount.', sourceNote: 'Nykaa official offers/coupons pages; dynamic promotion.', sourceUrl: 'https://www.nykaa.com/coupons-offers' },
  { platform: 'Swiggy', title: 'Official food offers and terms', code: null, minOrder: 0, expires: 'Check official page', category: 'food', audience: 'all', eligibilityNote: 'Restaurant, city, account, membership and cart eligibility vary.', howToApply: 'Open the official offer page or app, apply only an eligible offer and confirm checkout totals.', sourceNote: 'Swiggy official offers and terms; dynamic promotion.', sourceUrl: 'https://www.swiggy.com/food-offer-near-me' },
  { platform: 'Zomato', title: 'Official restaurant deals', code: null, minOrder: 0, expires: 'Check official page', category: 'food', audience: 'all', eligibilityNote: 'Merchant participation, restaurant, city, validity and eligibility vary.', howToApply: 'Open the official restaurant offer listing or app and confirm the deal before ordering.', sourceNote: 'Zomato official Deals Program and listings; dynamic promotion.', sourceUrl: 'https://www.zomato.com/policies/deals/customer-policy/' },
  { platform: 'Blinkit', title: 'Official Offer Zone', code: null, minOrder: 0, expires: 'Check official page', category: 'grocery', audience: 'all', eligibilityNote: 'Promo credits, vouchers and cashback can be product- or account-specific.', howToApply: 'Open the official Offer Zone or app, add eligible items and check the final total.', sourceNote: 'Blinkit official promotions and terms; dynamic promotion.', sourceUrl: 'https://www.blinkit.com/blog/discounts-deals-offers' },
  { platform: 'Zepto', title: 'Official Top Deals and Deal Store', code: null, minOrder: 0, expires: 'Check official page', category: 'grocery', audience: 'all', eligibilityNote: 'Vouchers and benefits vary by user, city, product and store.', howToApply: 'Open the official Top Deals or Deal Store and confirm the applicable voucher at checkout.', sourceNote: 'Zepto official deal pages; dynamic promotion.', sourceUrl: 'https://www.zepto.com/uncl/top-deals/e1a6fea7-5e16-4648-81f8-b162c2225141' },
  { platform: 'MakeMyTrip', title: 'Official travel offers', code: null, minOrder: 0, expires: 'Check official page', category: 'shop', audience: 'all', eligibilityNote: 'Route, inventory, fare, payment and itinerary eligibility vary.', howToApply: 'Open the official offer page, select the itinerary and confirm the final fare and terms.', sourceNote: 'MakeMyTrip official offer pages; dynamic promotion.', sourceUrl: 'https://www.makemytrip.com/flights/domestic-flight-offer.html' },
];

export const KEYWORDS: Record<string, string> = {
  iph: 'iphone 17 16 apple mobile smartphone 256gb ios electronics',
  app: 'airpods pro 2nd gen earbuds apple headphones audio earphones',
  hdp: 'headphones earphones audio anc over-ear wireless sony boat',
  shoe: 'shoes running sneakers footwear sneakers kicks trainers nike puma',
  bir: 'biryani chicken rice food meal lunch dinner non-veg hyderabadi eatclub swiggy zomato magicpin',
  piz: 'pizza food cheese italian dominos crust delivery margherita eatclub swiggy zomato',
  cof: 'coffee cafe cold espresso latte beverage drink iced',
  btr: 'butter chicken naan meal dinner curry gravy north indian food',
  bur: 'burger whopper veg burger meal fries snacks fast food',
  mlk: 'milk amul taaza gold dairy grocery fresh beverage quick-commerce',
  egg: 'eggs grocery poultry protein breakfast eggs pack farm',
  brd: 'bread grocery snacks brown bakery wheat toast multigrain',
};

export const CITIES = ['Hyderabad', 'Bengaluru', 'Mumbai', 'Delhi', 'Chennai', 'Pune', 'Kolkata', 'Ahmedabad'];
