export interface PlatformResearchRecord {
  id: string;
  name: string;
  category: string;
  domain: string;
  dealsUrls: string[];
  couponUrls: string[];
  claim: string;
  dynamicWarning: string;
  sources: string[];
}

/**
 * Official-source directory, not a hard-coded coupon feed. Promotion values,
 * dates, eligibility and codes must be rechecked on the linked partner page.
 */
export const PLATFORM_RESEARCH: PlatformResearchRecord[] = [
  {
    id: 'amazon-in',
    name: 'Amazon India',
    category: 'Marketplace & e-commerce',
    domain: 'https://www.amazon.in',
    dealsUrls: ['https://www.amazon.in/deals', 'https://www.amazon.in/gp/help/customer/display.html?nodeId=GPW59RAF7826AEFD'],
    couponUrls: ['https://www.amazon.in/b?ie=UTF8&node=14527413031', 'https://www.amazon.in/gp/help/customer/display.html?nodeId=GW2QNFK3F7T8ULDS'],
    claim: 'Official Deals and Promotions pages are available on Amazon.in.',
    dynamicWarning: 'Coupon validity, seller eligibility, expiry, payment method and checkout terms can change.',
    sources: ['https://www.amazon.in/deals', 'https://www.amazon.in/gp/help/customer/display.html?nodeId=GPW59RAF7826AEFD', 'https://www.amazon.in/gp/help/customer/display.html?nodeId=GW2QNFK3F7T8ULDS'],
  },
  {
    id: 'flipkart',
    name: 'Flipkart',
    category: 'Marketplace & e-commerce',
    domain: 'https://www.flipkart.com',
    dealsUrls: ['https://www.flipkart.com/offers-store'],
    couponUrls: ['https://www.flipkart.com/q/flipkart-coupons'],
    claim: 'Official Offers Store and coupon pages cover current campaigns and category promotions.',
    dynamicWarning: 'Codes, minimum spend, payment method, region and account eligibility are dynamic.',
    sources: ['https://www.flipkart.com/offers-store', 'https://www.flipkart.com/q/flipkart-coupons', 'https://www.flipkart.com/helpcentre'],
  },
  {
    id: 'meesho',
    name: 'Meesho',
    category: 'Marketplace & e-commerce',
    domain: 'https://www.meesho.com',
    dealsUrls: ['https://www.meesho.com/offer-store/pl/9v8'],
    couponUrls: [],
    claim: 'The official Offer Store is the verified destination for Meesho deals.',
    dynamicWarning: 'Product, account, app, location and campaign eligibility can change; no universal code is asserted.',
    sources: ['https://www.meesho.com/', 'https://www.meesho.com/offer-store/pl/9v8', 'https://meesho.io/'],
  },
  {
    id: 'myntra',
    name: 'Myntra',
    category: 'Fashion & lifestyle',
    domain: 'https://www.myntra.com',
    dealsUrls: ['https://www.myntra.com/shop/offers', 'https://www.myntra.com/special-offer'],
    couponUrls: ['https://www.myntra.com/myntra-coupons', 'https://www.myntra.com/myntra-coupon-offer'],
    claim: 'Official offers, special-offer and coupon pages are available on myntra.com.',
    dynamicWarning: 'Codes, minimum spends, exclusions, payment rules and expiry dates change frequently.',
    sources: ['https://www.myntra.com/', 'https://www.myntra.com/myntra-coupons', 'https://www.myntra.com/shop/offers', 'https://www.myntra.com/special-offer'],
  },
  {
    id: 'nykaa',
    name: 'Nykaa',
    category: 'Beauty & lifestyle',
    domain: 'https://www.nykaa.com',
    dealsUrls: ['https://www.nykaa.com/sp/offers-native/offers'],
    couponUrls: ['https://www.nykaa.com/coupons-offers', 'https://www.nykaa.com/coupons'],
    claim: 'Official Coupons & Offers and offers pages are available on nykaa.com.',
    dynamicWarning: 'Discounts, expiry, order thresholds, eligible products and app/web rules are dynamic.',
    sources: ['https://www.nykaa.com/', 'https://www.nykaa.com/who_are_we', 'https://www.nykaa.com/sp/offers-native/offers', 'https://www.nykaa.com/coupons-offers'],
  },
  {
    id: 'swiggy',
    name: 'Swiggy',
    category: 'Food delivery & convenience',
    domain: 'https://www.swiggy.com',
    dealsUrls: ['https://www.swiggy.com/food-offer-near-me'],
    couponUrls: ['https://www.swiggy.com/offer-terms'],
    claim: 'Official food-offers and offer-terms pages are available on swiggy.com.',
    dynamicWarning: 'Offers, participating restaurants, codes, dates and eligibility vary by account, city and checkout.',
    sources: ['https://www.swiggy.com/terms-and-conditions', 'https://www.swiggy.com/food-offer-near-me', 'https://www.swiggy.com/offer-terms'],
  },
  {
    id: 'zomato',
    name: 'Zomato',
    category: 'Food ordering & dining deals',
    domain: 'https://www.zomato.com',
    dealsUrls: ['https://www.zomato.com/mumbai/restoran?offers=1', 'https://www.zomato.com/policies/deals/customer-policy/'],
    couponUrls: [],
    claim: 'Official restaurant listings and Deals Program terms are available on zomato.com.',
    dynamicWarning: 'Merchant participation, discount, availability, validity and eligibility must be checked in the app or checkout.',
    sources: ['https://www.zomato.com/', 'https://www.zomato.com/policies/deals/customer-policy/', 'https://www.zomato.com/developer/integration/docs/glossary/order-discount-categories/'],
  },
  {
    id: 'blinkit',
    name: 'Blinkit',
    category: 'Quick commerce & groceries',
    domain: 'https://blinkit.com',
    dealsUrls: ['https://www.blinkit.com/blog/discounts-deals-offers'],
    couponUrls: [],
    claim: 'Official FAQ, terms and Offer Zone article describe Blinkit promotions and grocery delivery.',
    dynamicWarning: 'Promo credits, codes, vouchers and cashback can be modified or discontinued and may be product-specific.',
    sources: ['https://blinkit.com/faq', 'https://blinkit.com/terms', 'https://www.blinkit.com/blog/discounts-deals-offers'],
  },
  {
    id: 'zepto',
    name: 'Zepto',
    category: 'Quick commerce & groceries',
    domain: 'https://www.zepto.com',
    dealsUrls: ['https://www.zepto.com/uncl/top-deals/e1a6fea7-5e16-4648-81f8-b162c2225141', 'https://www.zepto.com/pip/deal-store/5752'],
    couponUrls: ['https://www.zepto.com/s/zepto-supersaver-monthly-milestones'],
    claim: 'Official Top Deals, Deal Store and Supersaver pages are available on zepto.com.',
    dynamicWarning: 'Vouchers and benefits vary by user, city, product, store and expiry; no universal code is asserted.',
    sources: ['https://www.zepto.com/', 'https://www.zepto.com/uncl/top-deals/e1a6fea7-5e16-4648-81f8-b162c2225141', 'https://www.zepto.com/pip/deal-store/5752', 'https://www.zepto.com/s/zepto-supersaver-monthly-milestones'],
  },
  {
    id: 'makemytrip',
    name: 'MakeMyTrip',
    category: 'Flights, hotels, buses & travel',
    domain: 'https://www.makemytrip.com',
    dealsUrls: ['https://www.makemytrip.com/', 'https://www.makemytrip.com/flights/domestic-flight-offer.html', 'https://www.makemytrip.com/international-flights/international-flight-offer.html'],
    couponUrls: ['https://promos.makemytrip.com/wow-terms-05112021.html'],
    claim: 'Official domestic, international and promotions pages cover travel offers and terms.',
    dynamicWarning: 'Inventory, fares, codes, validity, payment conditions and eligibility change by itinerary and account.',
    sources: ['https://www.makemytrip.com/about-us.html', 'https://www.makemytrip.com/flights/domestic-flight-offer.html', 'https://www.makemytrip.com/international-flights/international-flight-offer.html', 'https://promos.makemytrip.com/wow-terms-05112021.html'],
  },
  {
    id: 'ajio',
    name: 'AJIO',
    category: 'Fashion & lifestyle',
    domain: 'https://www.ajio.com',
    dealsUrls: ['https://www.ajio.com/offers'],
    couponUrls: ['https://www.ajio.com/coupon-faq'],
    claim: 'Official offers, coupon FAQ and promotion policy pages describe first-purchase and seasonal promotions.',
    dynamicWarning: 'Codes, selected products, user eligibility, stacking and withdrawal rules change by campaign.',
    sources: ['https://www.ajio.com/offers', 'https://www.ajio.com/ajio-sale-policy', 'https://www.ajio.com/coupon-faq'],
  },
  {
    id: 'bookmyshow',
    name: 'BookMyShow',
    category: 'Movies & entertainment',
    domain: 'https://in.bookmyshow.com',
    dealsUrls: ['https://in.bookmyshow.com/offers'],
    couponUrls: ['https://in.bookmyshow.com/offers'],
    claim: 'Official offers listing provides card-linked movie, entertainment and food-and-beverage promotions.',
    dynamicWarning: 'Card variant, cap, quota, city, cinema, fees and validity must be confirmed at checkout.',
    sources: ['https://in.bookmyshow.com/offers'],
  },
  {
    id: 'jiomart',
    name: 'JioMart',
    category: 'Grocery & shopping',
    domain: 'https://www.jiomart.com',
    dealsUrls: ['https://www.jiomart.com/offers'],
    couponUrls: ['https://www.jiomart.com/offers'],
    claim: 'Official offers page is the source directory for grocery and payment promotions.',
    dynamicWarning: 'Cart, pincode, payment, product and expiry conditions may not be published until checkout.',
    sources: ['https://www.jiomart.com/offers'],
  },
  {
    id: 'croma',
    name: 'Croma',
    category: 'Electronics & appliances',
    domain: 'https://www.croma.com',
    dealsUrls: ['https://www.croma.com/offers'],
    couponUrls: ['https://www.croma.com/offers'],
    claim: 'Official offers destination covers electronics, appliances, payment and seasonal promotions.',
    dynamicWarning: 'Store inventory, pin code, payment method, product exclusions and expiry are dynamic.',
    sources: ['https://www.croma.com/offers', 'https://www.croma.com/terms-and-conditions'],
  },
];
