import { CouponItem } from './types';

const official = (url: string, note: string): Pick<CouponItem, 'sourceUrl' | 'sourceNote' | 'isLive' | 'sourceType'> => ({
  sourceUrl: url,
  sourceNote: `${note} Values and eligibility can change; verify the final payable amount at checkout.`,
  isLive: true,
  sourceType: 'official',
});

const unofficial = (url: string, note: string): Pick<CouponItem, 'sourceUrl' | 'sourceNote' | 'isLive' | 'sourceType'> => ({
  sourceUrl: url,
  sourceNote: `${note} This is a third-party lead, not a partner-issued confirmation; verify the code, expiry and final saving on the partner checkout page.`,
  isLive: false,
  sourceType: 'unofficial',
});

const userSubmitted = (url: string): Pick<CouponItem, 'sourceUrl' | 'sourceNote' | 'isLive' | 'sourceType'> => ({
  sourceUrl: url,
  sourceNote: 'Code supplied by the user; DealNest has not independently verified activation, expiry, eligibility or discount. Test it on the official checkout page before payment.',
  isLive: false,
  sourceType: 'user_submitted',
});

const submittedCoupon = (platform: string, code: string, minOrder: number, category: CouponItem['category'], url: string): CouponItem => ({
  platform,
  title: 'User-submitted coupon — verify at checkout',
  code,
  minOrder,
  expires: 'Verify at checkout',
  category,
  audience: 'all',
  discount: 'Discount not independently verified',
  status: 'user_submitted_verify_checkout',
  eligibilityNote: 'User-submitted code; product, account, campaign and location eligibility must be checked on the partner page.',
  howToApply: `Open the official ${platform} page, apply ${code}, and confirm the final payable amount before payment.`,
  terms: minOrder ? `Minimum bill ₹${minOrder.toLocaleString('en-IN')} as supplied; activation and expiry are not independently verified.` : 'No minimum bill supplied; activation and expiry are not independently verified.',
  ...userSubmitted(url),
});

const USER_SUBMITTED_COUPONS: CouponItem[] = [
  submittedCoupon('AJIO', 'NEW20', 1500, 'fashion', 'https://www.ajio.com/offers'),
  submittedCoupon('AJIO', 'PLUS20AURA', 1500, 'fashion', 'https://www.ajio.com/offers'),
  submittedCoupon('AJIO', 'SHADELOVE', 1999, 'fashion', 'https://www.ajio.com/offers'),
  submittedCoupon('Libas', 'SALE100', 1999, 'fashion', 'https://www.libas.in/'),
  submittedCoupon('Nykaa Fashion', 'NFFLAT10', 0, 'fashion', 'https://www.nykaafashion.com/'),
  submittedCoupon('Nykaa Fashion', 'NFSEP300', 3000, 'fashion', 'https://www.nykaafashion.com/'),
  submittedCoupon('AJIOGRAM', 'AJIOGRAM10', 1200, 'fashion', 'https://www.ajio.com/offers'),
  submittedCoupon('XYXX Crew', 'GBXYXX10', 799, 'fashion', 'https://xyxxcrew.com/'),
  submittedCoupon('Myntra', 'BFF500', 2999, 'fashion', 'https://www.myntra.com/'),
  submittedCoupon('Myntra', 'MYNTRA500', 2199, 'fashion', 'https://www.myntra.com/'),
  submittedCoupon('Myntra', 'MYNTRAEXCLUSIVE1', 300, 'fashion', 'https://www.myntra.com/'),
  submittedCoupon('Myntra', 'FWDNEW200', 399, 'fashion', 'https://www.myntra.com/'),
  submittedCoupon('Myntra', 'MYNTRA300', 3499, 'fashion', 'https://www.myntra.com/'),
  submittedCoupon('Myntra', 'FWDU15', 300, 'fashion', 'https://www.myntra.com/'),
  submittedCoupon('Myntra', 'EXTRA500', 2500, 'fashion', 'https://www.myntra.com/'),
  submittedCoupon('Myntra', 'FTWMEGAOFF', 0, 'fashion', 'https://www.myntra.com/'),
  submittedCoupon('Nykaa', 'EXTRA20%', 500, 'beauty', 'https://www.nykaa.com/coupons-offers'),
  submittedCoupon('Nykaa', 'EXTRA400I', 1500, 'beauty', 'https://www.nykaa.com/coupons-offers'),
  submittedCoupon('Nykaa', 'NEW15', 0, 'beauty', 'https://www.nykaa.com/coupons-offers'),
  submittedCoupon('Nykaa', 'NYK3RD', 0, 'beauty', 'https://www.nykaa.com/coupons-offers'),
  submittedCoupon('Decathlon', 'NC100', 1499, 'shop', 'https://www.decathlon.in/'),
];

export const VERIFIED_COUPONS: CouponItem[] = ([
  {
    platform: 'Amazon India', title: 'Electronics sale: Zebronics USB extension cable', code: null,
    discount: '81% off; ₹116.63 sale price vs ₹599 MRP', minOrder: 0, expires: 'Not published',
    category: 'shop', audience: 'all', status: 'active_visible_offer', eligibilityNote: 'Visible on the official Electronics & accessories sale listing; stock, seller, account and delivery eligibility vary.',
    howToApply: 'Open the official listing, select the item, and confirm the displayed sale price and delivery terms before payment.', terms: 'Product-level sale price; no reusable code published. Availability is time-sensitive.',
    ...official('https://www.amazon.in/b?ie=UTF8&node=83208890031', 'Amazon India official sale listing'),
  },
  {
    platform: 'Amazon India', title: 'Samsung Galaxy Tab S12 Ultra: coupon shown', code: null,
    discount: '₹15,000 off coupon shown on the listing', minOrder: 0, expires: 'Not published',
    category: 'shop', audience: 'all', status: 'active_visible_offer', eligibilityNote: 'Specific configuration and account/product eligibility must be confirmed on the product page.',
    howToApply: 'Open the product listing, select the displayed coupon if available, and confirm the reduced payable amount at checkout.', terms: 'No code or full coupon terms are published on the category page.',
    ...official('https://www.amazon.in/b?ie=UTF8&node=83208890031', 'Amazon India official sale listing'),
  },
  {
    platform: 'Flipkart', title: 'Big Billion Days card instant discount', code: null,
    discount: 'Up to 10% instant discount', minOrder: 0, expires: 'End date not published',
    category: 'shop', audience: 'bank', status: 'active_upcoming', eligibilityNote: 'Eligible Axis Bank or ICICI Bank card transactions during the stated sale window.',
    howToApply: 'Shop an eligible item during the sale, pay with an eligible card, and confirm the discount before payment.', terms: 'Official page states terms apply; product, card, cap and transaction exclusions may vary.',
    ...official('https://www.flipkart.com/big-billion-days-store', 'Flipkart official Big Billion Days page'),
  },
  {
    platform: 'Flipkart', title: 'Supermoney first transaction offer', code: null,
    discount: '10% off on the first transaction', minOrder: 0, expires: 'End date not published',
    category: 'shop', audience: 'new', status: 'active_upcoming', eligibilityNote: 'First eligible transaction made using Supermoney.',
    howToApply: 'Choose Supermoney at checkout and confirm the first-transaction discount before paying.', terms: 'Official page states terms apply; product and user eligibility may vary.',
    ...official('https://www.flipkart.com/big-billion-days-store', 'Flipkart official Big Billion Days page'),
  },
  {
    platform: 'Myntra', title: 'Extra ₹300 off for new users', code: 'MYNTRA300',
    discount: 'Up to 90% off plus ₹300 extra off', minOrder: 1699, expires: 'Not published',
    category: 'shop', audience: 'new', status: 'visible_source_verify_checkout', eligibilityNote: 'New users on the Myntra app; selected products and accounts may apply.',
    howToApply: 'Add eligible items meeting the threshold, enter MYNTRA300 at checkout, and verify the discount before payment.', terms: 'Offer visibility and full exclusions require confirmation in the Myntra checkout.',
    ...official('https://www.myntra.com/myntra-coupon-offer', 'Myntra offer page'),
  },
  {
    platform: 'Myntra', title: 'All-users tiered discount', code: 'STACKUP',
    discount: '₹400 off above ₹2,499 or ₹800 off above ₹5,000', minOrder: 2499, expires: 'Not published',
    category: 'shop', audience: 'all', status: 'visible_source_verify_checkout', eligibilityNote: 'Applicable categories and product exclusions must be confirmed in the bag.',
    howToApply: 'Reach the applicable cart threshold, enter STACKUP, and verify the tier applied before payment.', terms: 'The higher tier requires ₹5,000; terms and expiry are not published in the visible offer.',
    ...official('https://www.myntra.com/myntra-coupons', 'Myntra coupon listing'),
  },
  {
    platform: 'AJIO', title: 'New-user first purchase offer', code: 'FIRSTBUY',
    discount: 'Extra 30–33% off', minOrder: 0, expires: 'Not published',
    category: 'shop', audience: 'new', status: 'visible_official_verify_checkout', eligibilityNote: 'First-ever AJIO website purchase on selected products; one use per user.',
    howToApply: 'Add selected products, choose Apply Coupon, enter FIRSTBUY, and confirm the discount in the bag.', terms: 'AJIO policy says the offer may be modified or withdrawn and cannot generally be combined with other AJIO promotions.',
    ...official('https://www.ajio.com/offers', 'AJIO official offers page'),
  },
  {
    platform: 'AJIO', title: 'Free shipping for eligible users', code: 'FREE149',
    discount: 'Free shipping; amount not published', minOrder: 0, expires: 'Not published',
    category: 'shop', audience: 'all', status: 'visible_official_verify_checkout', eligibilityNote: 'Eligible users and products only; the visible offer does not publish the complete rule set.',
    howToApply: 'Enter FREE149 in the bag and confirm that shipping is removed before payment.', terms: 'Shipping eligibility, product exclusions and withdrawal rules are controlled by AJIO.',
    ...official('https://www.ajio.com/offers', 'AJIO official offers page'),
  },
  {
    platform: 'Nykaa', title: 'Extra 10% off on first web order', code: 'NEW10',
    discount: 'Extra 10% off', minOrder: 0, expires: 'Not published',
    category: 'shop', audience: 'new', status: 'active_visible_verify_checkout', eligibilityNote: 'First order on the Nykaa website.',
    howToApply: 'Enter NEW10 in the Nykaa coupon section and verify the discount before payment.', terms: 'Nykaa’s visible listing says see details; exclusions and expiry are not published.',
    ...official('https://www.nykaa.com/coupons-offers', 'Nykaa official Coupons & Offers page'),
  },
  {
    platform: 'Nykaa', title: 'Flat ₹400 off on app orders', code: 'EXTRA400I',
    discount: 'Flat ₹400 off', minOrder: 1500, expires: 'Not published',
    category: 'shop', audience: 'all', status: 'active_visible_verify_checkout', eligibilityNote: 'Nykaa app orders above ₹1,500 as stated in the official listing.',
    howToApply: 'Use the Nykaa app, enter EXTRA400I, and confirm the applied discount before payment.', terms: 'Full exclusions and expiry are not published in the visible listing.',
    ...official('https://www.nykaa.com/coupons-offers', 'Nykaa official Coupons & Offers page'),
  },
  {
    platform: 'Swiggy', title: 'Food orders above ₹159', code: null,
    discount: 'Up to 50% off, maximum ₹100', minOrder: 159, expires: 'Not published',
    category: 'food', audience: 'all', status: 'visible_source_verify_checkout', eligibilityNote: 'Select restaurants and food varieties; not valid on flash-sale items.',
    howToApply: 'Choose an eligible restaurant and apply the offer shown in the Swiggy cart; confirm final fees and savings.', terms: 'Offer-specific code and expiry are not published. Swiggy’s general terms say offers may not be clubbed.',
    ...official('https://www.swiggy.com/offer-terms', 'Swiggy official offer terms'),
  },
  {
    platform: 'Swiggy Instamart', title: 'Free shipping above ₹299', code: null,
    discount: 'Up to 90% off listings plus free shipping', minOrder: 299, expires: 'Not published',
    category: 'grocery', audience: 'all', status: 'visible_source_verify_checkout', eligibilityNote: 'Availability depends on city, store, cart and account.',
    howToApply: 'Add eligible Instamart items, meet the cart threshold and confirm the fee line at checkout.', terms: 'No universal code or offer expiry is published; delivery and service charges can still vary.',
    ...official('https://www.swiggy.com/instamart', 'Swiggy Instamart official page'),
  },
  {
    platform: 'Zomato', title: 'Gold free delivery benefit', code: null,
    discount: 'Free delivery within 7 km', minOrder: 0, expires: 'Not published',
    category: 'food', audience: 'membership', status: 'active_visible_verify_checkout', eligibilityNote: 'Zomato Gold members and participating restaurants within 7 km as stated on the official page.',
    howToApply: 'Use an eligible Gold membership and confirm delivery fees in the Zomato app before ordering.', terms: 'Other fees and restaurant exclusions are not published on the visible homepage.',
    ...official('https://www.zomato.com/', 'Zomato official homepage'),
  },
  {
    platform: 'Blinkit', title: 'Paytm payment cashback', code: null,
    discount: 'Cashback up to ₹100', minOrder: 750, expires: 'Not published',
    category: 'grocery', audience: 'all', status: 'visible_source_verify_checkout', eligibilityNote: 'Paytm payment; source states up to two uses per customer.',
    howToApply: 'Choose Paytm at Blinkit payment and confirm the cashback disclosure before placing the order.', terms: 'Cashback may be modified or withdrawn; Blinkit charges and product restrictions are confirmed at checkout.',
    ...official('https://blinkit.com/terms', 'Blinkit official terms'),
  },
  {
    platform: 'Blinkit', title: 'Free delivery above ₹199', code: null,
    discount: 'Free delivery', minOrder: 199, expires: 'Not published',
    category: 'grocery', audience: 'all', status: 'visible_source_verify_checkout', eligibilityNote: 'All products and users were stated in the visible offer listing; serviceability still applies.',
    howToApply: 'Reach the cart threshold and verify the delivery charge before payment.', terms: 'Handling, convenience, platform, surge and small-cart fees may still apply.',
    ...official('https://blinkit.com/terms', 'Blinkit official terms'),
  },
  {
    platform: 'Zepto', title: 'QuickSave200 extra discount', code: 'QUICKSAVE200',
    discount: 'Up to ₹200 additional discount; source advertises up to 95% off listings', minOrder: 1299, expires: 'Not published',
    category: 'grocery', audience: 'all', status: 'visible_source_verify_checkout', eligibilityNote: 'Account, product, city and cart eligibility must be checked in the Zepto app.',
    howToApply: 'Enter QUICKSAVE200 in the Zepto checkout coupon field and confirm the applied amount.', terms: 'Promotional vouchers can lapse, expire or be revoked without notice under Zepto terms.',
    ...official('https://www.zepto.com/s/terms-of-service', 'Zepto terms and promotion listing'),
  },
  {
    platform: 'MakeMyTrip', title: 'First booking savings', code: null,
    discount: 'Up to 25% off on the first booking', minOrder: 0, expires: 'Not published',
    category: 'travel', audience: 'new', status: 'active_visible_verify_checkout', eligibilityNote: 'First booking; product category and exact eligibility vary by itinerary.',
    howToApply: 'Select an eligible itinerary and confirm the offer in the booking flow before payment.', terms: 'Official homepage states offer terms apply; no universal code is published.',
    ...official('https://www.makemytrip.com/', 'MakeMyTrip official homepage'),
  },
  {
    platform: 'BookMyShow', title: 'YES Bank MARQUEE BOGO movie ticket', code: null,
    discount: 'Buy 1 get 1 movie ticket free', minOrder: 0, expires: '31 Dec 2026 23:59',
    category: 'entertainment', audience: 'bank', status: 'active_official', eligibilityNote: 'YES Bank MARQUEE Credit Card; web and mobile availability stated on the official offer listing.',
    howToApply: 'Choose the offer at BookMyShow checkout, pay with the eligible card and confirm the complimentary ticket before payment.', terms: 'Ticket cap, frequency, cinema and fee exclusions are not published in the listing.',
    ...official('https://in.bookmyshow.com/offers', 'BookMyShow official offers listing'),
  },
  {
    platform: 'BookMyShow', title: 'IDFC FIRST Bank Private Card offer', code: null,
    discount: 'Up to ₹750 off; usable twice monthly', minOrder: 0, expires: '31 Mar 2027 23:59',
    category: 'entertainment', audience: 'bank', status: 'active_official', eligibilityNote: 'IDFC FIRST Bank Private Credit Card; Movies/FnB and/or Non-movies as listed.',
    howToApply: 'Select the offer in BookMyShow checkout, pay with the eligible card and confirm the final price.', terms: 'Minimum spend and fee exclusions are not published in the listing.',
    ...official('https://in.bookmyshow.com/offers', 'BookMyShow official offers listing'),
  },
  {
    platform: 'JioMart', title: 'Fruits and vegetables offer', code: null,
    discount: 'Flat ₹25 off', minOrder: 149, expires: 'Not published',
    category: 'grocery', audience: 'all', status: 'visible_source_verify_checkout', eligibilityNote: 'Fruits and vegetables orders; current cart eligibility must be confirmed.',
    howToApply: 'Add eligible items, meet the cart threshold and verify the offer in JioMart checkout.', terms: 'No universal code or current expiry is published in the accessible official page.',
    ...official('https://www.jiomart.com/offers', 'JioMart official offers page'),
  },
  {
    platform: 'JioMart', title: 'AU Bank grocery offer', code: null,
    discount: '10% off up to ₹300', minOrder: 2000, expires: 'Not published',
    category: 'grocery', audience: 'bank', status: 'visible_source_verify_checkout', eligibilityNote: 'Grocery purchases paid with an eligible AU Bank card.',
    howToApply: 'Pay with an eligible AU Bank card and verify the discount cap before payment.', terms: 'Card variants, stacking and expiry require checkout confirmation.',
    ...official('https://www.jiomart.com/offers', 'JioMart official offers page'),
  },
  {
    platform: 'AJIO', title: 'Official fashion offers directory', code: null,
    discount: 'Campaign discounts and promo codes vary by product', minOrder: 0, expires: 'Check official page',
    category: 'fashion', audience: 'all', status: 'official_directory_verify_checkout', eligibilityNote: 'Product, account, size, seller and campaign eligibility vary.',
    howToApply: 'Open the official offers page, select an eligible fashion item and confirm the offer in the bag.', terms: 'No universal code is published in the directory record; expiry and exclusions must be checked at checkout.',
    ...official('https://www.ajio.com/offers', 'AJIO official fashion offers page'),
  },
  {
    platform: 'Nykaa', title: 'Official beauty offers directory', code: null,
    discount: 'Beauty, skincare and makeup promotions vary by campaign', minOrder: 0, expires: 'Check official page',
    category: 'beauty', audience: 'all', status: 'official_directory_verify_checkout', eligibilityNote: 'Brand, product, app/web, account and minimum-cart rules vary.',
    howToApply: 'Open the official coupons page, select eligible beauty products and verify the saving in the bag.', terms: 'No universal code is published in the directory record; exclusions and expiry are partner-controlled.',
    ...official('https://www.nykaa.com/coupons-offers', 'Nykaa official beauty offers page'),
  },
  {
    platform: 'Tata 1mg', title: 'Official pharmacy and lab-test offers', code: null,
    discount: 'Product, medicine and diagnostic promotions vary by city', minOrder: 0, expires: 'Check official page',
    category: 'medical', audience: 'all', status: 'official_directory_verify_checkout', eligibilityNote: 'Prescription, pin code, medicine, lab, patient and account rules apply.',
    howToApply: 'Open the official offers page, select an eligible service or product and verify the final payable amount.', terms: 'Prescription requirements, exclusions, delivery and expiry must be confirmed before payment.',
    ...official('https://www.1mg.com/offers', 'Tata 1mg official offers page'),
  },
  {
    platform: 'Tanishq', title: 'Official jewellery offers directory', code: null,
    discount: 'Store, collection and payment promotions vary', minOrder: 0, expires: 'Check official page',
    category: 'jewelry', audience: 'all', status: 'official_directory_verify_checkout', eligibilityNote: 'Collection, store, making-charge, metal-price and payment terms vary.',
    howToApply: 'Open the official jewellery site, select the eligible collection and confirm the final price and terms.', terms: 'Jewellery pricing, taxes, making charges, stock and promotion expiry require confirmation at checkout.',
    ...official('https://www.tanishq.co.in/', 'Tanishq official jewellery site'),
  },
  {
    platform: 'Cult.fit', title: 'Official fitness membership offers', code: null,
    discount: 'Membership and class promotions vary by city and plan', minOrder: 0, expires: 'Check official page',
    category: 'fitness', audience: 'all', status: 'official_directory_verify_checkout', eligibilityNote: 'City, centre, plan, new-member and renewal eligibility vary.',
    howToApply: 'Open the official membership page, choose the city and plan, and verify the final payable amount.', terms: 'Trial, renewal, cancellation, centre and plan restrictions must be confirmed before purchase.',
    ...official('https://www.cult.fit/', 'Cult.fit official membership site'),
  },
  {
    platform: 'Uber', title: 'Official ride promo directory', code: null,
    discount: 'Ride credits and promotional fares vary by route', minOrder: 0, expires: 'Check official app',
    category: 'mobility', audience: 'all', status: 'official_directory_verify_checkout', eligibilityNote: 'City, route, account, ride type and payment eligibility vary.',
    howToApply: 'Open the official app or promotion page, choose the ride and confirm the fare and promo before booking.', terms: 'Promo availability, caps, surge, cancellation and service fees are confirmed in the booking flow.',
    ...official('https://www.uber.com/in/en/ride/uber-promotions/', 'Uber India official promotions page'),
  },
  {
    platform: 'Urban Company', title: 'Official home-service offers directory', code: null,
    discount: 'Service and city promotions vary by provider', minOrder: 0, expires: 'Check official app',
    category: 'services', audience: 'all', status: 'official_directory_verify_checkout', eligibilityNote: 'City, service, slot, provider, account and first-booking rules vary.',
    howToApply: 'Open the official service page, choose a service and slot, and confirm the final payable amount.', terms: 'Service scope, taxes, add-ons, cancellation and expiry must be checked before booking.',
    ...official('https://www.urbancompany.com/', 'Urban Company official service site'),
  },
  {
    platform: 'Cars24', title: 'Official auto-service offers directory', code: null,
    discount: 'Inspection, service and vehicle promotions vary', minOrder: 0, expires: 'Check official page',
    category: 'auto', audience: 'all', status: 'official_directory_verify_checkout', eligibilityNote: 'City, vehicle, inspection, service and appointment availability vary.',
    howToApply: 'Open the official Cars24 page, choose the relevant service and confirm the quote and terms.', terms: 'Vehicle condition, taxes, documentation, appointment and cancellation terms require confirmation.',
    ...official('https://www.cars24.com/', 'Cars24 official auto services site'),
  },
  {
    platform: 'HDFC Bank', title: 'Official card-offer directory', code: null,
    discount: 'Partner cashback and instant discounts vary by merchant', minOrder: 0, expires: 'Check official page',
    category: 'pay', audience: 'bank', status: 'official_directory_verify_checkout', eligibilityNote: 'Eligible card variant, merchant, transaction channel and monthly cap apply.',
    howToApply: 'Open the official card-offers page, select the merchant offer and verify the discount before payment.', terms: 'Bank terms, caps, exclusions, EMI rules and settlement timing must be confirmed with the partner.',
    ...official('https://offers.smartbuy.hdfcbank.com/', 'HDFC Bank official SmartBuy offers page'),
  },
  {
    platform: 'Croma', title: 'Official electronics offers directory', code: null,
    discount: 'Electronics and appliance promotions vary by product', minOrder: 0, expires: 'Check official page',
    category: 'shop', audience: 'all', status: 'official_directory_verify_checkout', eligibilityNote: 'Product, pin code, stock, payment, bank and delivery eligibility vary.',
    howToApply: 'Open the official offers page, select the product and verify the displayed discount and final total.', terms: 'No universal code is published in the directory record; offer exclusions and expiry require checkout confirmation.',
    ...official('https://www.croma.com/offers', 'Croma official electronics offers page'),
  },
  {
    platform: 'CouponDunia', title: 'Third-party shopping coupon leads', code: null,
    discount: 'User-facing coupon listings and cashback leads vary by merchant', minOrder: 0, expires: 'Check source and partner checkout',
    category: 'shop', audience: 'all', status: 'third_party_lead_unverified', eligibilityNote: 'Aggregator listing only; merchant, account, product and payment eligibility are not verified by DealNest.',
    howToApply: 'Open the listing, copy a displayed code only if present, then test it on the official partner checkout and confirm the final total.', terms: 'DealNest does not guarantee activation, rate, expiry, stacking or cashback settlement for third-party leads.',
    ...unofficial('https://www.coupondunia.in/', 'CouponDunia third-party coupon and cashback directory'),
  },
  {
    platform: 'GrabOn', title: 'Third-party food and travel coupon leads', code: null,
    discount: 'Aggregator-listed promo leads vary by merchant', minOrder: 0, expires: 'Check source and partner checkout',
    category: 'food', audience: 'all', status: 'third_party_lead_unverified', eligibilityNote: 'Aggregator listing only; restaurant, route, account and payment eligibility must be checked with the partner.',
    howToApply: 'Open the listing, copy a code only if present, and verify the applied saving on the official partner checkout.', terms: 'Third-party listing may be expired, limited, duplicated or unavailable in the user’s city.',
    ...unofficial('https://www.grabon.in/', 'GrabOn third-party promotion directory'),
  },
  {
    platform: 'CashKaro', title: 'Third-party cashback and coupon leads', code: null,
    discount: 'Cashback rates and coupon leads vary by merchant', minOrder: 0, expires: 'Check source and partner checkout',
    category: 'pay', audience: 'all', status: 'third_party_lead_unverified', eligibilityNote: 'Cashback tracking, exclusions, payment method and account eligibility are controlled by the third party and merchant.',
    howToApply: 'Review the third-party terms, open the official merchant link, and confirm both the coupon and final payable amount before ordering.', terms: 'Cashback is not an instant discount and may require tracking, validation and a waiting period.',
    ...unofficial('https://cashkaro.com/', 'CashKaro third-party cashback and coupon directory'),
  },
  {
    platform: 'CouponDunia', title: 'Third-party beauty and fashion coupon leads', code: null,
    discount: 'Aggregator-listed fashion and beauty promotions vary', minOrder: 0, expires: 'Check source and partner checkout',
    category: 'fashion', audience: 'all', status: 'third_party_lead_unverified', eligibilityNote: 'Product, brand, account, minimum cart and merchant eligibility are not independently verified.',
    howToApply: 'Review the aggregator listing, test any displayed code on the official partner page, and verify the final saving.', terms: 'Do not treat the listing as an active guarantee; merchant terms and expiry take precedence.',
    ...unofficial('https://www.coupondunia.in/', 'CouponDunia third-party fashion and beauty directory'),
  },
  {
    platform: 'JioMart', title: 'Official grocery deal directory', code: null,
    discount: 'Grocery, household and fresh-food promotions vary by cart', minOrder: 0, expires: 'Check official page',
    category: 'grocery', audience: 'all', status: 'official_directory_verify_checkout', eligibilityNote: 'City, cart, product, stock and account eligibility vary.',
    howToApply: 'Open the official offers page, add eligible products, and verify the offer and delivery charges in checkout.', terms: 'No universal code or guaranteed expiry is published in the directory record.',
    ...official('https://www.jiomart.com/offers', 'JioMart official grocery offers page'),
  },
  {
    platform: 'GrabOn', title: 'Third-party Flipkart grocery coupon leads', code: null,
    discount: 'Aggregator-listed grocery promotions vary', minOrder: 0, expires: 'Check source and partner checkout',
    category: 'grocery', audience: 'all', status: 'third_party_lead_unverified', eligibilityNote: 'Third-party listing only; code, city, account and product eligibility require partner confirmation.',
    howToApply: 'Review the listing, copy a code only if shown, open the official partner checkout and confirm the final saving.', terms: 'Do not treat aggregator snippets as a guarantee; the merchant checkout controls validity.',
    ...unofficial('https://www.grabon.in/flipkart-supermart-coupons/', 'GrabOn third-party Flipkart grocery coupon directory'),
  },
  {
    platform: 'GrabOn', title: 'Third-party Zepto coupon leads', code: null,
    discount: 'Aggregator-listed quick-commerce promotions vary', minOrder: 0, expires: 'Check source and partner checkout',
    category: 'grocery', audience: 'all', status: 'third_party_lead_unverified', eligibilityNote: 'Zepto city, store, account, product and cart rules must be checked in the app.',
    howToApply: 'Review the listing, test any displayed code in Zepto checkout, and verify the final amount before payment.', terms: 'Offer rates and codes can expire or be restricted without notice.',
    ...unofficial('https://www.grabon.in/zepto-coupons/', 'GrabOn third-party Zepto coupon directory'),
  },
  {
    platform: 'DesiDime', title: 'Third-party Swiggy deal and coupon leads', code: null,
    discount: 'Community-listed food promotions vary by restaurant and city', minOrder: 0, expires: 'Check source and partner checkout',
    category: 'food', audience: 'all', status: 'third_party_lead_unverified', eligibilityNote: 'Community listing; restaurant, city, account, payment and cart eligibility require confirmation.',
    howToApply: 'Open the deal thread, review the latest terms, then verify the applied offer and final fees in Swiggy checkout.', terms: 'Community posts may be stale, limited or unavailable for the user’s account.',
    ...unofficial('https://www.desidime.com/stores/swiggy', 'DesiDime third-party Swiggy deal directory'),
  },
  {
    platform: 'Zoutons', title: 'Third-party grocery coupon directory', code: null,
    discount: 'Multi-store grocery coupons and offers vary', minOrder: 0, expires: 'Check source and partner checkout',
    category: 'grocery', audience: 'all', status: 'third_party_lead_unverified', eligibilityNote: 'Aggregator listing only; merchant terms and eligibility take precedence.',
    howToApply: 'Open the source listing, review the code terms, and confirm the final saving on the official merchant page.', terms: 'No DealNest guarantee of activation, expiry, stacking or cashback settlement.',
    ...unofficial('https://zoutons.com/category/groceries', 'Zoutons third-party grocery coupon directory'),
  },
  ...USER_SUBMITTED_COUPONS,
] as CouponItem[]).filter(coupon => coupon.sourceType !== 'unofficial' && Boolean(coupon.code));
